### ISSUE TITLE
GitHub Action 自动编译Vue项目并发布

### ISSUE THREAD

**Issue by 0fengzi0** [0fengzi0/Blog#21]
脚本内容
```yml
name: buildAndDeploy

env:
  TZ: Asia/Shanghai

on:
  # 当master分支提交时
  push:
    branches: 
      - master

# 开始任务
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    
    # 安装和构建
    - name: Install and Build
      run: |
        yarn
        yarn run 5ixf
        
    - name: Update dist folder to repository
      env:
        # 你的GitHub名字
        GITHUB_USERNAME: "0fengzi0"
        # 你的邮箱
        EMAIL: "5ixf@5ixf.vip"
        # GitHub Pages仓库名
        DIST_REPO: "VOCALTTS-dist"
        # GitHub Token
        GITHUB_TOKEN: ${{ secrets.G_TOKEN }}
        
      run: |
        git config --global user.email $GITHUB_USERNAME
        git config --global user.name $EMAIL
        
        cd dist/admin && git init && git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://$GITHUB_TOKEN@github.com/$GITHUB_USERNAME/$DIST_REPO.git" master:master
```
